{% set name = "google-cloud-workflows" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-workflows-{{ version }}.tar.gz
  sha256: 5111b43fdfd461684b090bcbf1ec0ac7fdf85765618885654f527847a414e236

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=2.8.0,<3.0.0dev
    - proto-plus >=1.15.0,<2.0.0dev
    - protobuf >=3.19.0,<4.0.0dev

test:
  imports:
    - google.cloud.workflows
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-workflows
  license: Apache-2.0
  license_file: LICENSE
  summary: Cloud Workflows API
  description: |
    Cloud Workflows API: Orchestrate and automateGoogle Cloud and HTTP-based
    API services with serverless workflows.
  dev_url: https://github.com/googleapis/python-workflows
  doc_url: https://googleapis.dev/python/workflows/latest/index.html

extra:
  recipe-maintainers:
    - xylar
    - parthea
